name: "Hello Actions"
description: "Greet New user"
author: "jackson.oliveira.rs@gmail.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "jack"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
